"""add ticket model

Revision ID: 8e202f83cff9
Revises: 9f2d8d702732
Create Date: 2024-10-21 22:36:19.482321

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8e202f83cff9"
down_revision: Union[str, None] = "9f2d8d702732"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticket",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("available", "booked", "sold", name="ticketstatusenum"),
            nullable=True,
        ),
        sa.Column(
            "type",
            sa.Enum("adult", "discount", "child", name="tickettypeenum"),
            nullable=False,
        ),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("booked_at", sa.DateTime(), nullable=True),
        sa.Column("purchased_at", sa.DateTime(), nullable=True),
        sa.Column("event_date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["user.id"],
            name=op.f("fk_ticket_customer_id_user"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["event.id"], name=op.f("fk_ticket_event_id_event")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ticket")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ticket")
    # ### end Alembic commands ###
