"""add user and user role

Revision ID: 932f53546752
Revises: a6f934489210
Create Date: 2024-05-28 12:18:10.526712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '932f53546752'
down_revision: Union[str, None] = 'a6f934489210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text("TIMEZONE('ASIA/YEKATERINBURG', CURRENT_TIMESTAMP)"),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text("TIMEZONE('ASIA/YEKATERINBURG', CURRENT_TIMESTAMP)"),
                              nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('surname', sa.String(), nullable=False),
                    sa.Column('patronymic', sa.String(), nullable=False),
                    sa.Column('hashed_password', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('user_id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('user_role',
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text("TIMEZONE('ASIA/YEKATERINBURG', CURRENT_TIMESTAMP)"),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text("TIMEZONE('ASIA/YEKATERINBURG', CURRENT_TIMESTAMP)"),
                              nullable=False),
                    sa.Column('user_role_id', sa.BigInteger(), nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('role', sa.Enum('admin', 'employee', name='userroleenum'), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('user_role_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.drop_table('user')
    # ### end Alembic commands ###
