"""empty message

Revision ID: c3c34546ce5b
Revises: 
Create Date: 2024-04-06 14:56:03.041990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3c34546ce5b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('ASIA/YEKATERINBURG', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('ASIA/YEKATERINBURG', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('age_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Enum('adults', 'teenagers', 'kids', name='ageenum'), nullable=False),
    sa.PrimaryKeyConstraint('age_id')
    )
    op.create_table('genre',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('ASIA/YEKATERINBURG', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('ASIA/YEKATERINBURG', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('genre_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Enum('excursion', 'master_class', 'spectacle', 'exhibition', 'interactive_lesson', 'concert', 'genealogy', 'lecture', 'creative_meeting', 'festival', 'artist_talk', 'film_screening', name='categoryenum'), nullable=False),
    sa.PrimaryKeyConstraint('genre_id')
    )
    op.create_table('location',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('ASIA/YEKATERINBURG', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('ASIA/YEKATERINBURG', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Enum('cachka_house', 'metenkov_house', 'l52', 'water_tower', 'makletsky_house', 'memorial_complex', name='areaenum'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('ticket',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('ASIA/YEKATERINBURG', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('ASIA/YEKATERINBURG', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('pushkin_card', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_table('event',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('ASIA/YEKATERINBURG', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('ASIA/YEKATERINBURG', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('genre_id', sa.BigInteger(), nullable=True),
    sa.Column('ticket_id', sa.BigInteger(), nullable=True),
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.Column('age_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('disabilities', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['age_id'], ['age.age_id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.ticket_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_table('ticket')
    op.drop_table('location')
    op.drop_table('genre')
    op.drop_table('age')
    # ### end Alembic commands ###
