"""add event tags

Revision ID: dd97fe1ac292
Revises: b6b9cfe338ab
Create Date: 2024-05-18 19:01:51.381211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd97fe1ac292'
down_revision: Union[str, None] = 'b6b9cfe338ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_tag',
    sa.Column('event_tag_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_tag')
    # ### end Alembic commands ###
